Vagrant.configure(2) do |config|
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "bento/debian-7.8-i386"
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # VirtualBox:
  config.vm.provider "bento/debian-7.8-i386" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true
     # Customize the amount of memory on the VM:
     vb.memory = "1024"
  end
  # run init.sh
  config.vm.provision "shell", path: "init.sh"
end
