VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "jhcook/osx-elcapitan-10.11"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.ssh.insert_key = false

  config.vm.provider "vagrant-hello-world" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true
     # Customize the amount of memory on the VM:
     vb.memory = "1024"
  end
end
